name: docs
channels:
  - conda-forge
  - numba
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.3=h516909a_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h6acc77f_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - black=22.1.0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - bokeh=2.4.2=py310hff52083_0
  - boost-cpp=1.74.0=h6cacc03_7
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py310h6acc77f_1003
  - build=0.7.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=ha00ac49_1009
  - certifi=2021.10.8=py310hff52083_1
  - cffi=1.15.0=py310h0fdd8cc_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.0.0=h9a35b8e_0
  - chardet=4.0.0=py310hff52083_2
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.4=py310hff52083_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cmarkgfm=0.7.0=py310h6acc77f_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.11.0=py310hff52083_0
  - conda-build=3.21.8=py310hff52083_0
  - conda-package-handling=1.7.3=py310h6acc77f_1
  - conda-souschef=2.1.1=pyhd8ed1ab_0
  - coverage=6.3.2=py310h5764c6d_1
  - cryptography=36.0.1=py310h685ca39_0
  - curl=7.81.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.5.1=py310h122e73d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.4=pyhd8ed1ab_0
  - docutils=0.17.1=py310hff52083_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.6=h27087fc_0
  - filelock=3.6.0=pyhd8ed1ab_0
  - fiona=1.8.21=py310hfb73927_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=ha180cfb_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py310h6acc77f_0
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gdal=3.4.1=py310hce6f0df_4
  - geojson=2.5.0=py_0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.2=h9c3ff4c_0
  - geotiff=1.7.0=h6593c0a_6
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - git=2.35.0=pl5321hc30692c_0
  - glob2=0.7=py_0
  - grayskull=1.1.2=pyhd8ed1ab_0
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_103
  - icu=69.1=h9c3ff4c_0
  - identify=2.4.11=pyhd8ed1ab_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.2=py310hff52083_0
  - importlib_metadata=4.11.2=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.9.1=py310hfdc917e_0
  - ipython=8.0.1=py310hff52083_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py310hff52083_0
  - jeepney=0.7.1=pyhd8ed1ab_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - json-c=0.15=h98cffda_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py310hff52083_7
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py310hff52083_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kealib=1.4.14=h87e4c3c_3
  - keyring=23.4.0=py310hff52083_2
  - kiwisolver=1.3.2=py310h91b1402_1
  - krb5=1.19.2=hcc1bbae_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.81.0=h2574ce0_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgdal=3.4.1=he20be3c_4
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_12
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=13_linux64_openblas
  - liblief=0.11.5=h9c3ff4c_1
  - libllvm11=11.1.0=hf817b99_3
  - libllvm13=13.0.1=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - librttopo=1.1.0=hf69c175_9
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h0e567f8_14
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvmlite=0.38.0=py310hee97dad_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.0=py310h5764c6d_0
  - matplotlib-base=3.5.1=py310h23f4a51_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py310h6acc77f_1005
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py310hff52083_4
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - nbclient=0.5.11=pyhd8ed1ab_0
  - nbconvert=6.4.2=py310hff52083_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h9c3ff4c_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.7=pyhd8ed1ab_0
  - nodeenv=1.6.0=pyhd8ed1ab_0
  - notebook=6.4.8=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.74=hb5efdd6_0
  - numba=0.55.1=py310hc55943c_0
  - numpy=1.21.5=py310h647a097_0
  - numpydoc=1.2=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - osmnx=1.1.2=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py310hb5077e9_0
  - pandoc=2.17.1.1=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patchelf=0.14.5=h58526e2_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - pep517=0.12.0=py310hff52083_1
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py310he619898_2
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.8.2=pyhd8ed1ab_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py310hff52083_2
  - poppler=22.01.0=ha39eefc_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.2=h2510834_0
  - pre-commit=2.17.0=py310hff52083_0
  - progressbar2=4.0.0=pyhd8ed1ab_0
  - proj=8.2.1=h277dcde_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - prompt_toolkit=3.0.27=hd8ed1ab_0
  - psutil=5.9.0=py310h6acc77f_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.11.5=py310h122e73d_1
  - pycosat=0.6.3=py310h6acc77f_1009
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py310h9e0d750_1
  - pyqt=5.12.3=py310hff52083_8
  - pyqt-impl=5.12.3=py310h1f8e252_8
  - pyqt5-sip=4.19.18=py310h122e73d_8
  - pyqtchart=5.12=py310hfcd6d55_8
  - pyqtwebengine=5.12.1=py310hfcd6d55_8
  - pyrsistent=0.18.1=py310h6acc77f_0
  - pysocks=1.7.1=py310hff52083_4
  - pytest=7.0.1=py310hff52083_0
  - python=3.10.2=h85951f9_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py310hff52083_0
  - python-utils=3.1.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h6acc77f_3
  - pyzmq=22.3.0=py310h675a958_1
  - qt=5.12.9=ha98a1a1_5
  - qtconsole=5.2.2=pyhd8ed1ab_1
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.0.1=pyhd8ed1ab_0
  - rapidfuzz=1.9.1=py310hb5077e9_0
  - rasterio=1.2.10=py310h5e0f756_4
  - readline=8.1=h46c0cb4_0
  - readme_renderer=27.0=pyh9f0ad1d_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-toolbelt=0.9.1=py_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - ripgrep=13.0.0=habb4d0f_1
  - rtree=0.9.7=py310hbdcdc62_3
  - ruamel.yaml=0.17.21=py310h6acc77f_0
  - ruamel.yaml.clib=0.2.6=py310h6acc77f_0
  - ruamel.yaml.jinja2=0.2.4=py_1
  - ruamel_yaml=0.15.80=py310h6acc77f_1006
  - scikit-learn=1.0.2=py310h1246948_0
  - scipy=1.8.0=py310hea5193d_1
  - secretstorage=3.3.1=py310hff52083_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.9.3=py310hff52083_0
  - shapely=1.8.0=py310h1b8dd88_5
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.4.0=pyh6c4a22f_1
  - sphinx_rtd_theme=1.0.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_1
  - sqlite=3.37.0=h9cd32fc_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - stdlib-list=0.7.0=py_2
  - terminado=0.13.1=py310hff52083_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.6.3=h1e4a385_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py310h6acc77f_2
  - tqdm=4.63.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - twine=3.8.0=pyhd8ed1ab_0
  - typed-ast=1.5.2=py310h6acc77f_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzcode=2021e=h7f98852_0
  - tzdata=2021e=he74cb21_0
  - ukkonen=1.0.1=py310h91b1402_1
  - unicodedata2=14.0.0=py310h6acc77f_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - virtualenv=20.13.2=py310hff52083_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py310hff52083_1
  - xerces-c=3.2.3=h8ce2273_4
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.2.0=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
prefix: /home/portmann/miniconda3/envs/dyntapy-dev
